spring:
  cloud:
    config:
      name: config_client # 需要从github上读取的资源名称，无需后缀
      profile: dev
      label: master
      uri: http://localhost:3344

  config:
    import:
      configserver:http://localhost:3344
  application:
    name: springcloud-config-client-3355