server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: com.chen.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chenbing

## Eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/, http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001 # 修改eureka上的默认描述信息

## 监控信息
info:
  app.name: springcloud-demo
  company.name: chen